### ISSUE TITLE
version.php

### ISSUE THREAD

**Issue by nmoller** [mgage/wwlink#1]
Instead of 
$plugin->component = 'wwlink';
it should say
$plugin->component = 'block_wwlink';

**Comment by mgage** [comment]
Hi Nelson.   Thanks very much.  I'll fix it.  I can use the help of those more experienced with moodle module development.  I'd like to polish these two modules so that they are easily used by those already using moodle for mathematics homework.  Let me know if you start them regularly.

**Comment by nmoller** [comment]
I've added some small corrections to wwassign too. Thanks for sharing those modules, if I find other issues, I'll add to a fork.
